scene:
  scene_path: "/PATH/TO/YOUR/OWN"
  dataset_name: "cocomap"
  test_cameras: False
  colmap_images: "images"
  colmap_eval_hold: 8
  downscale_ratio: 1
  white_background: False
  device: "cuda:0"
  
pipeline:
  convert_shs_python: False
  compute_cov3d_python: False
  debug: False
  seed: 0

model:
  sh_degree: 3
  model_dir: "/PATH/TO/YOUR/OWN"
  load_iteration: -1
  device: "cuda:0"

fusion:
  out_dir: "/PATH/TO/YOUR/OWN"
  model_2d: openseg

distill:
  model_3d: MinkUNet34A
  model_dir: "/PATH/TO/YOUR/OWN"
  text_model: openseg
  voxel_size: 0.02
  iteration: 100
  feature_type: all

eval:
  eval_mode: labelmap # choose from 2d, 3d, 2d_and_3d, pretrained, labelmap
  width: 648
  height: 484
  pred_on_3d: True
  feature_fusion: concat # choose from concat, argmax

