scene:
  dataset_name: "scannet_20"
  scene_path: "/PATH/TO/YOUR/OWN"
  test_cameras: False
  colmap_images: "images"
  colmap_eval_hold: 8
  downscale_ratio: 1
  white_background: False
  device: "cuda:0"
  
pipeline:
  convert_shs_python: False
  compute_cov3d_python: False
  debug: False
  seed: 0

model:
  sh_degree: 3
  model_dir: "/PATH/TO/YOUR/OWN"
  load_iteration: 10000
  device: "cuda:0"
  pretrained_weights_path:
    - "./weights/openseg_exported_clip"
    - "ViT-L/14@336px"

fusion:
  out_dir: "/PATH/TO/YOUR/OWN"

distill:
  model_3d: MinkUNet34A
  model_dir: "/PATH/TO/YOUR/OWN"
  voxel_size: 0.02
  iteration: 100
  feature_type: all

eval:
  model_2d: openseg
  width: 648
  height: 484
  pred_on_3d: True
  feature_fusion: argmax # choose from concat, argmax, mean 

