scene:
  scene_path: "/home/guojun/winshare/nerf/datasets/neural_3d_video/coffee_martini/colmap_0"
  dataset_name: "scannet_20"
  test_cameras: False
  colmap_images: "images"
  colmap_eval_hold: 8
  downscale_ratio: 0.25
  white_background: False
  device: "cuda:0"
  
pipeline:
  convert_shs_python: False
  compute_cov3d_python: False
  debug: False
  seed: 0

model:
  sh_degree: 3
  model_dir: "../nerf/Dynamic3DGaussians/output/timestep150/coffee_martini" #"./output/coffee_martini"
  dynamic: True
  load_iteration: -1
  num_timesteps: 150
  device: "cuda:0"

fusion:
  img_dim: [676, 507]
  model_2d: samclip # choose from openseg, groundingsam, vlpart
  depth: render # choose from image, render, surface, none
  depth_scale: 1000.0
  use_sam_mask: False
  visibility_threshold: 0.05
  cut_boundary: 10
  n_split_points: 9999999 #80000
  num_rand_file_per_scene: 1 #5
  out_dir: "./fusion"

render:
  fusion_dir: "./fusion/room_samclip.pt"
  view_scale: 1
  dynamic_fps: 20
