scene:
  scene_path: "/PATH/TO/YOUR/OWN"
  dataset_name: "cocomap"
  test_cameras: False
  colmap_images: "images"
  colmap_eval_hold: 8
  downscale_ratio: 1
  white_background: False
  device: "cuda:0"
  
pipeline:
  convert_shs_python: False
  compute_cov3d_python: False
  debug: False
  seed: 0

model:
  sh_degree: 3
  model_dir: "/PATH/TO/YOUR/OWN"
  dynamic: True
  load_iteration: -1
  num_timesteps: 150
  device: "cuda:0"

fusion:
  img_dim: [640, 360]
  num_workers: 8
  model_2d: vlpart # choose from openseg, lseg, samclip, vlpart
  depth: surface # choose from image, render, surface, none
  depth_scale: 1000.0
  visibility_threshold: 0.01
  cut_boundary: 10
  outlier_threshold: -2.0
  n_split_points: 9999999
  num_rand_file_per_scene: 1
  out_dir: "/PATH/TO/YOUR/OWN"
