scene:
  scene_path: "/PATH/TO/YOUR/OWN"
  dataset_name: "cocomap"
  test_cameras: False
  colmap_images: "images"
  colmap_eval_hold: 8
  downscale_ratio: 0.5
  white_background: False
  device: "cuda:0"
  
pipeline:
  convert_shs_python: False
  compute_cov3d_python: False
  debug: False
  seed: 0

model:
  sh_degree: 3
  model_dir: "/PATH/TO/YOUR/OWN"
  dynamic: False
  load_iteration: -1
  device: "cuda:0"

fusion:
  img_dim: [540, 960]
  num_workers: 8
  model_2d: openseg # choose from openseg, lseg, samclip, vlpart
  depth: render # choose from image, render, surface, none
  depth_scale: 1000.0
  visibility_threshold: 0.02
  outlier_threshold: -2.0
  cut_boundary: 10
  n_split_points: 99999999 #50000
  num_rand_file_per_scene: 1 #5
  out_dir: "/PATH/TO/YOUR/OWN"
