scene:
  scene_path: "/PATH/TO/YOUR/OWN"
  dataset_name: "cocomap"
  test_cameras: False
  colmap_images: "images"
  colmap_eval_hold: 8
  downscale_ratio: 1
  white_background: False
  device: "cuda:0"
  
pipeline:
  convert_shs_python: False
  compute_cov3d_python: False
  debug: False
  seed: 0

model:
  sh_degree: 3
  model_dir: "/PATH/TO/YOUR/OWN"
  dynamic: False
  load_iteration: -1
  device: "cuda:0"

render:
  fusion_dir: "/PATH/TO/YOUR/OWN/*.pt"
  model_2d: openseg # choose from openseg, lseg, samclip, vlpart
